// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: app/fllcker/command/command.proto

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the user, as the core carries it in session metadata. Required.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Addresses to act on. Empty means every address the user currently holds.
	//
	// Passing the whole list in one call matters: kicking address by address
	// leaves a window in which the client dropped by an earlier call is already
	// back on an address the caller has not named yet.
	Ips []string `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	// How long to refuse this user at these addresses. 0 kicks without blocking,
	// which on its own achieves little: a client reconnects in about the time it
	// takes to notice the drop.
	BanSeconds    uint32 `protobuf:"varint,3,opt,name=ban_seconds,json=banSeconds,proto3" json:"ban_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *KickRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *KickRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *KickRequest) GetBanSeconds() uint32 {
	if x != nil {
		return x.BanSeconds
	}
	return 0
}

type KickResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Distinct connections closed. For Hysteria2 this counts QUIC streams rather
	// than clients: a kick there ends the stream while the client stays
	// authenticated at the transport layer, and it is the block that turns away
	// whatever it opens next.
	Closed int32 `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	// When the block lifts, or 0 if none was placed. Rounded up, so waiting until
	// this moment never returns while the block is still live.
	BannedUntil   int64 `protobuf:"varint,2,opt,name=banned_until,json=bannedUntil,proto3" json:"banned_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickResponse) Reset() {
	*x = KickResponse{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResponse) ProtoMessage() {}

func (x *KickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResponse.ProtoReflect.Descriptor instead.
func (*KickResponse) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *KickResponse) GetClosed() int32 {
	if x != nil {
		return x.Closed
	}
	return 0
}

func (x *KickResponse) GetBannedUntil() int64 {
	if x != nil {
		return x.BannedUntil
	}
	return 0
}

type SessionIP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ip    string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Live connections from this address.
	Conns int32 `protobuf:"varint,2,opt,name=conns,proto3" json:"conns,omitempty"`
	// When the address first appeared. Answers "who arrived when".
	Since int64 `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	// When this address last opened a stream. Answers "is it still doing
	// anything": an address left behind by a network switch stops opening
	// streams, while a device in use opens them continuously.
	LastSeen int64 `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// 0 when not blocked.
	BannedUntil   int64 `protobuf:"varint,5,opt,name=banned_until,json=bannedUntil,proto3" json:"banned_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionIP) Reset() {
	*x = SessionIP{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIP) ProtoMessage() {}

func (x *SessionIP) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIP.ProtoReflect.Descriptor instead.
func (*SessionIP) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *SessionIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SessionIP) GetConns() int32 {
	if x != nil {
		return x.Conns
	}
	return 0
}

func (x *SessionIP) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *SessionIP) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *SessionIP) GetBannedUntil() int64 {
	if x != nil {
		return x.BannedUntil
	}
	return 0
}

type UserSessions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ips           []*SessionIP           `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSessions) Reset() {
	*x = UserSessions{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSessions) ProtoMessage() {}

func (x *UserSessions) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSessions.ProtoReflect.Descriptor instead.
func (*UserSessions) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *UserSessions) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSessions) GetIps() []*SessionIP {
	if x != nil {
		return x.Ips
	}
	return nil
}

type ListSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means every user.
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSessions        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *ListSessionsResponse) GetUsers() []*UserSessions {
	if x != nil {
		return x.Users
	}
	return nil
}

type BanEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Until         int64                  `protobuf:"varint,3,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanEntry) Reset() {
	*x = BanEntry{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanEntry) ProtoMessage() {}

func (x *BanEntry) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanEntry.ProtoReflect.Descriptor instead.
func (*BanEntry) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *BanEntry) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *BanEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BanEntry) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

type ListBansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means every user.
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBansRequest) Reset() {
	*x = ListBansRequest{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBansRequest) ProtoMessage() {}

func (x *ListBansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBansRequest.ProtoReflect.Descriptor instead.
func (*ListBansRequest) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{7}
}

func (x *ListBansRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListBansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expired entries are never reported, even before they are collected.
	Bans          []*BanEntry `protobuf:"bytes,1,rep,name=bans,proto3" json:"bans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBansResponse) Reset() {
	*x = ListBansResponse{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBansResponse) ProtoMessage() {}

func (x *ListBansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBansResponse.ProtoReflect.Descriptor instead.
func (*ListBansResponse) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *ListBansResponse) GetBans() []*BanEntry {
	if x != nil {
		return x.Bans
	}
	return nil
}

type UnbanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required.
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Empty lifts every block on this user.
	Ips           []string `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanRequest) Reset() {
	*x = UnbanRequest{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanRequest) ProtoMessage() {}

func (x *UnbanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanRequest.ProtoReflect.Descriptor instead.
func (*UnbanRequest) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *UnbanRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UnbanRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type UnbanResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when there was nothing to lift.
	Lifted        bool `protobuf:"varint,1,opt,name=lifted,proto3" json:"lifted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanResponse) Reset() {
	*x = UnbanResponse{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanResponse) ProtoMessage() {}

func (x *UnbanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanResponse.ProtoReflect.Descriptor instead.
func (*UnbanResponse) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *UnbanResponse) GetLifted() bool {
	if x != nil {
		return x.Lifted
	}
	return false
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_fllcker_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_fllcker_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_fllcker_command_command_proto_rawDescGZIP(), []int{11}
}

var File_app_fllcker_command_command_proto protoreflect.FileDescriptor

const file_app_fllcker_command_command_proto_rawDesc = "" +
	"\n" +
	"!app/fllcker/command/command.proto\x12\x18xray.app.fllcker.command\"V\n" +
	"\vKickRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\x12\x1f\n" +
	"\vban_seconds\x18\x03 \x01(\rR\n" +
	"banSeconds\"I\n" +
	"\fKickResponse\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\x05R\x06closed\x12!\n" +
	"\fbanned_until\x18\x02 \x01(\x03R\vbannedUntil\"\x87\x01\n" +
	"\tSessionIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x14\n" +
	"\x05conns\x18\x02 \x01(\x05R\x05conns\x12\x14\n" +
	"\x05since\x18\x03 \x01(\x03R\x05since\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12!\n" +
	"\fbanned_until\x18\x05 \x01(\x03R\vbannedUntil\"[\n" +
	"\fUserSessions\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x125\n" +
	"\x03ips\x18\x02 \x03(\v2#.xray.app.fllcker.command.SessionIPR\x03ips\"+\n" +
	"\x13ListSessionsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"T\n" +
	"\x14ListSessionsResponse\x12<\n" +
	"\x05users\x18\x01 \x03(\v2&.xray.app.fllcker.command.UserSessionsR\x05users\"F\n" +
	"\bBanEntry\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x14\n" +
	"\x05until\x18\x03 \x01(\x03R\x05until\"'\n" +
	"\x0fListBansRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"J\n" +
	"\x10ListBansResponse\x126\n" +
	"\x04bans\x18\x01 \x03(\v2\".xray.app.fllcker.command.BanEntryR\x04bans\"6\n" +
	"\fUnbanRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\"'\n" +
	"\rUnbanResponse\x12\x16\n" +
	"\x06lifted\x18\x01 \x01(\bR\x06lifted\"\b\n" +
	"\x06Config2\x9b\x03\n" +
	"\x0eFllckerService\x12W\n" +
	"\x04Kick\x12%.xray.app.fllcker.command.KickRequest\x1a&.xray.app.fllcker.command.KickResponse\"\x00\x12o\n" +
	"\fListSessions\x12-.xray.app.fllcker.command.ListSessionsRequest\x1a..xray.app.fllcker.command.ListSessionsResponse\"\x00\x12c\n" +
	"\bListBans\x12).xray.app.fllcker.command.ListBansRequest\x1a*.xray.app.fllcker.command.ListBansResponse\"\x00\x12Z\n" +
	"\x05Unban\x12&.xray.app.fllcker.command.UnbanRequest\x1a'.xray.app.fllcker.command.UnbanResponse\"\x00Bj\n" +
	"\x1ccom.xray.app.fllcker.commandP\x01Z-github.com/xtls/xray-core/app/fllcker/command\xaa\x02\x18Xray.App.Fllcker.Commandb\x06proto3"

var (
	file_app_fllcker_command_command_proto_rawDescOnce sync.Once
	file_app_fllcker_command_command_proto_rawDescData []byte
)

func file_app_fllcker_command_command_proto_rawDescGZIP() []byte {
	file_app_fllcker_command_command_proto_rawDescOnce.Do(func() {
		file_app_fllcker_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_fllcker_command_command_proto_rawDesc), len(file_app_fllcker_command_command_proto_rawDesc)))
	})
	return file_app_fllcker_command_command_proto_rawDescData
}

var file_app_fllcker_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_app_fllcker_command_command_proto_goTypes = []any{
	(*KickRequest)(nil),          // 0: xray.app.fllcker.command.KickRequest
	(*KickResponse)(nil),         // 1: xray.app.fllcker.command.KickResponse
	(*SessionIP)(nil),            // 2: xray.app.fllcker.command.SessionIP
	(*UserSessions)(nil),         // 3: xray.app.fllcker.command.UserSessions
	(*ListSessionsRequest)(nil),  // 4: xray.app.fllcker.command.ListSessionsRequest
	(*ListSessionsResponse)(nil), // 5: xray.app.fllcker.command.ListSessionsResponse
	(*BanEntry)(nil),             // 6: xray.app.fllcker.command.BanEntry
	(*ListBansRequest)(nil),      // 7: xray.app.fllcker.command.ListBansRequest
	(*ListBansResponse)(nil),     // 8: xray.app.fllcker.command.ListBansResponse
	(*UnbanRequest)(nil),         // 9: xray.app.fllcker.command.UnbanRequest
	(*UnbanResponse)(nil),        // 10: xray.app.fllcker.command.UnbanResponse
	(*Config)(nil),               // 11: xray.app.fllcker.command.Config
}
var file_app_fllcker_command_command_proto_depIdxs = []int32{
	2,  // 0: xray.app.fllcker.command.UserSessions.ips:type_name -> xray.app.fllcker.command.SessionIP
	3,  // 1: xray.app.fllcker.command.ListSessionsResponse.users:type_name -> xray.app.fllcker.command.UserSessions
	6,  // 2: xray.app.fllcker.command.ListBansResponse.bans:type_name -> xray.app.fllcker.command.BanEntry
	0,  // 3: xray.app.fllcker.command.FllckerService.Kick:input_type -> xray.app.fllcker.command.KickRequest
	4,  // 4: xray.app.fllcker.command.FllckerService.ListSessions:input_type -> xray.app.fllcker.command.ListSessionsRequest
	7,  // 5: xray.app.fllcker.command.FllckerService.ListBans:input_type -> xray.app.fllcker.command.ListBansRequest
	9,  // 6: xray.app.fllcker.command.FllckerService.Unban:input_type -> xray.app.fllcker.command.UnbanRequest
	1,  // 7: xray.app.fllcker.command.FllckerService.Kick:output_type -> xray.app.fllcker.command.KickResponse
	5,  // 8: xray.app.fllcker.command.FllckerService.ListSessions:output_type -> xray.app.fllcker.command.ListSessionsResponse
	8,  // 9: xray.app.fllcker.command.FllckerService.ListBans:output_type -> xray.app.fllcker.command.ListBansResponse
	10, // 10: xray.app.fllcker.command.FllckerService.Unban:output_type -> xray.app.fllcker.command.UnbanResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_app_fllcker_command_command_proto_init() }
func file_app_fllcker_command_command_proto_init() {
	if File_app_fllcker_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_fllcker_command_command_proto_rawDesc), len(file_app_fllcker_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_fllcker_command_command_proto_goTypes,
		DependencyIndexes: file_app_fllcker_command_command_proto_depIdxs,
		MessageInfos:      file_app_fllcker_command_command_proto_msgTypes,
	}.Build()
	File_app_fllcker_command_command_proto = out.File
	file_app_fllcker_command_command_proto_goTypes = nil
	file_app_fllcker_command_command_proto_depIdxs = nil
}
