// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: app/fllcker/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FllckerService_Kick_FullMethodName         = "/xray.app.fllcker.command.FllckerService/Kick"
	FllckerService_ListSessions_FullMethodName = "/xray.app.fllcker.command.FllckerService/ListSessions"
	FllckerService_ListBans_FullMethodName     = "/xray.app.fllcker.command.FllckerService/ListBans"
	FllckerService_Unban_FullMethodName        = "/xray.app.fllcker.command.FllckerService/Unban"
)

// FllckerServiceClient is the client API for FllckerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FllckerServiceClient interface {
	Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	ListBans(ctx context.Context, in *ListBansRequest, opts ...grpc.CallOption) (*ListBansResponse, error)
	Unban(ctx context.Context, in *UnbanRequest, opts ...grpc.CallOption) (*UnbanResponse, error)
}

type fllckerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFllckerServiceClient(cc grpc.ClientConnInterface) FllckerServiceClient {
	return &fllckerServiceClient{cc}
}

func (c *fllckerServiceClient) Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickResponse)
	err := c.cc.Invoke(ctx, FllckerService_Kick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fllckerServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, FllckerService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fllckerServiceClient) ListBans(ctx context.Context, in *ListBansRequest, opts ...grpc.CallOption) (*ListBansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBansResponse)
	err := c.cc.Invoke(ctx, FllckerService_ListBans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fllckerServiceClient) Unban(ctx context.Context, in *UnbanRequest, opts ...grpc.CallOption) (*UnbanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbanResponse)
	err := c.cc.Invoke(ctx, FllckerService_Unban_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FllckerServiceServer is the server API for FllckerService service.
// All implementations must embed UnimplementedFllckerServiceServer
// for forward compatibility.
type FllckerServiceServer interface {
	Kick(context.Context, *KickRequest) (*KickResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	ListBans(context.Context, *ListBansRequest) (*ListBansResponse, error)
	Unban(context.Context, *UnbanRequest) (*UnbanResponse, error)
	mustEmbedUnimplementedFllckerServiceServer()
}

// UnimplementedFllckerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFllckerServiceServer struct{}

func (UnimplementedFllckerServiceServer) Kick(context.Context, *KickRequest) (*KickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kick not implemented")
}
func (UnimplementedFllckerServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedFllckerServiceServer) ListBans(context.Context, *ListBansRequest) (*ListBansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBans not implemented")
}
func (UnimplementedFllckerServiceServer) Unban(context.Context, *UnbanRequest) (*UnbanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unban not implemented")
}
func (UnimplementedFllckerServiceServer) mustEmbedUnimplementedFllckerServiceServer() {}
func (UnimplementedFllckerServiceServer) testEmbeddedByValue()                        {}

// UnsafeFllckerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FllckerServiceServer will
// result in compilation errors.
type UnsafeFllckerServiceServer interface {
	mustEmbedUnimplementedFllckerServiceServer()
}

func RegisterFllckerServiceServer(s grpc.ServiceRegistrar, srv FllckerServiceServer) {
	// If the following call panics, it indicates UnimplementedFllckerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FllckerService_ServiceDesc, srv)
}

func _FllckerService_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FllckerServiceServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FllckerService_Kick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FllckerServiceServer).Kick(ctx, req.(*KickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FllckerService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FllckerServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FllckerService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FllckerServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FllckerService_ListBans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FllckerServiceServer).ListBans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FllckerService_ListBans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FllckerServiceServer).ListBans(ctx, req.(*ListBansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FllckerService_Unban_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FllckerServiceServer).Unban(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FllckerService_Unban_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FllckerServiceServer).Unban(ctx, req.(*UnbanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FllckerService_ServiceDesc is the grpc.ServiceDesc for FllckerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FllckerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.fllcker.command.FllckerService",
	HandlerType: (*FllckerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kick",
			Handler:    _FllckerService_Kick_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _FllckerService_ListSessions_Handler,
		},
		{
			MethodName: "ListBans",
			Handler:    _FllckerService_ListBans_Handler,
		},
		{
			MethodName: "Unban",
			Handler:    _FllckerService_Unban_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/fllcker/command/command.proto",
}
